import typer
from rich.console import Console
from typing import Optional
import os
import json
import webbrowser
import subprocess
from venturalitica.scanner import BOMScanner

app = typer.Typer()
console = Console()

@app.command()
def scan(target: str = "."):
    """
    Scans the target directory to generate a CycloneDX ML-BOM.
    """
    console.print(f"[bold green]Scanning target:[/bold green] {target}")
    
    try:
        scanner = BOMScanner(target)
        output = scanner.scan()
        
        output_file = os.path.join(target, "bom.json")
        with open(output_file, "w") as f:
            f.write(output)
            
        console.print(f"[bold green]✓ BOM generated:[/bold green] {output_file}")
        console.print(f"Found {len(scanner.bom.components)} components.")
        
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] {e}")

@app.command()
def ui():
    """
    Launches the Venturalitica Local Compliance Dashboard.
    """
    console.print("[bold green]🚀 Launching Venturalitica UI...[/bold green]")
    
    # Path to dashboard.py
    dashboard_path = os.path.join(os.path.dirname(__file__), "dashboard.py")
    
    if not os.path.exists(dashboard_path):
        console.print(f"[bold red]Error:[/bold red] Dashboard file not found at {dashboard_path}")
        raise typer.Exit(code=1)
    
    try:
        # Run streamlit as a subprocess
        subprocess.run(["streamlit", "run", dashboard_path])
    except KeyboardInterrupt:
        console.print("\n[yellow]Dashboard stopped.[/yellow]")
    except Exception as e:
        console.print(f"[bold red]Failed to launch dashboard:[/bold red] {e}")

@app.command()
def doc(output: str = "Annex_IV.md"):
    """
    Generates a draft of the EU AI Act Annex IV.2 Technical Documentation.
    Uses the project BOM and local audit results.
    """
    console.print(f"[bold blue]📄 Generating Technical Documentation:[/bold blue] {output}")
    
    # 1. Load context
    bom = {}
    if os.path.exists("bom.json"):
        with open("bom.json", "r") as f:
            bom = json.load(f)
    else:
        console.print("[yellow]Warning:[/yellow] bom.json not found. Run 'venturalitica scan' first.")
        
    results = []
    if os.path.exists(".venturalitica/results.json"):
        with open(".venturalitica/results.json", "r") as f:
            results = json.load(f)
            
    # 2. Generate Draft (reusing logic from dashboard but simplified for CLI)
    components = bom.get('components', [])
    model_names = [c['name'] for c in components if c['type'] == 'machine-learning-model']
    passed_count = sum(1 for r in results if r.get('passed')) if results else 0
    total_count = len(results) if results else 0
    
    content = f"""# EU AI Act: Annex IV Technical Documentation
Generated by Venturalitica CLI v0.1.0

## 1. General description
**Intended Purpose:** [PENDING USER INPUT]
**Hardware:** [PENDING USER INPUT]

## 2. Technical implementation
This AI System incorporates {len(components)} technical modules, including: {', '.join(model_names) if model_names else 'standard architectures'}.
The system leverages local governance tracking for automated compliance oversight.

## 3. Risk management system
The system is integrated with the Venturalitica Risk Management framework.
Current validation status: {passed_count}/{total_count} controls passing in the latest local audit.
"""
    
    try:
        with open(output, "w") as f:
            f.write(content)
        console.print(f"[bold green]✓ Documentation draft created:[/bold green] {output}")
    except Exception as e:
        console.print(f"[bold red]Error generating documentation:[/bold red] {e}")

if __name__ == "__main__":
    app()
